version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=get-samuraisv2
    env_file:
      - ./.env
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: bash -c "npx prisma migrate dev | npm run start:dev auth"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/get-samuraisv2?schema=public&sslmode=disable
    depends_on:
      postgres:
        condition: service_started
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
